apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payment-service-role
  namespace: payment
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/instance: payment-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: banking-platform
    app.kubernetes.io/managed-by: kubectl
    environment: production
rules:
  # Read ConfigMaps
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

  # Read Services
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch

  # Read Endpoints
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch

  # Read Pods (Service Discovery / Diagnostics)
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
