apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/instance: payment-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: banking-platform
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "1.0.0"
    environment: production
type: Opaque
stringData:
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "paymentdb"
  DB_USERNAME: "payment_user"
  DB_PASSWORD: "ChangeMe@123"

  REDIS_HOST: "redis.cache.svc.cluster.local"
  REDIS_PORT: "6379"

  JWT_SECRET: "ReplaceWithVeryStrongJWTSecret"

  SPRING_DATASOURCE_USERNAME: "payment_user"
  SPRING_DATASOURCE_PASSWORD: "ChangeMe@123"
